window.GAME_DATA = {
  categories: [
    { id: "geral", label: "Geral / Todas" },
    { id: "futebol", label: "Futebol" },
    { id: "carros", label: "Carros" },
    { id: "comidas", label: "Comidas" },
    { id: "jogos", label: "Jogos" },
    { id: "filmes", label: "Filmes e séries" },
    { id: "animais", label: "Animais" },
    { id: "lugares", label: "Países e lugares" },
    { id: "marcas", label: "Marcas" },
    { id: "tecnologia", label: "Tecnologia" },
    { id: "esportes", label: "Esportes" },
    { id: "personagens", label: "Personagens" }
  ],

  questions: [
    { id: "fut-01", category: "futebol", prompt: "Melhor jogador de futebol", letters: "ACDFGJLMNPRSTV" },
    { id: "fut-02", category: "futebol", prompt: "Jogador que você escolheria para decidir uma final", letters: "ACDFGJLMNPRSTV" },
    { id: "fut-03", category: "futebol", prompt: "Melhor time de futebol", letters: "ABCFGLMPRSTV" },
    { id: "fut-04", category: "futebol", prompt: "Time com a torcida mais marcante", letters: "ABCFGLMPRSTV" },
    { id: "fut-05", category: "futebol", prompt: "Jogador mais habilidoso", letters: "ACDFGJLMNPRSTV" },
    { id: "fut-06", category: "futebol", prompt: "Melhor goleiro", letters: "ACDEGJLMNPRSTV" },
    { id: "fut-07", category: "futebol", prompt: "Melhor atacante", letters: "ACDFGJLMNPRSTV" },
    { id: "fut-08", category: "futebol", prompt: "Camisa de time mais bonita", letters: "ABCFGLMPRSTV" },

    { id: "car-01", category: "carros", prompt: "Melhor carro para viajar", letters: "ACFHMPRSTV" },
    { id: "car-02", category: "carros", prompt: "Carro que você teria na garagem", letters: "ABCFHMPRSTV" },
    { id: "car-03", category: "carros", prompt: "Carro mais bonito", letters: "ABCFHMPRSTV" },
    { id: "car-04", category: "carros", prompt: "Melhor carro para o dia a dia", letters: "ACFHMPRSTV" },
    { id: "car-05", category: "carros", prompt: "Melhor carro esportivo", letters: "ABCFGLMPRSTV" },
    { id: "car-06", category: "carros", prompt: "Marca de carro mais desejada", letters: "ABCFHLMPRSTV" },
    { id: "car-07", category: "carros", prompt: "Carro com melhor presença", letters: "ABCFHMPRSTV" },
    { id: "car-08", category: "carros", prompt: "Melhor carro custo-benefício", letters: "ACFHMPRSTV" },

    { id: "food-01", category: "comidas", prompt: "Comida mais gostosa", letters: "ABCEFLMPST" },
    { id: "food-02", category: "comidas", prompt: "Melhor comida para pedir à noite", letters: "ABCEFLMPST" },
    { id: "food-03", category: "comidas", prompt: "Melhor sobremesa", letters: "ABCMPT" },
    { id: "food-04", category: "comidas", prompt: "Melhor lanche", letters: "ABCHMPST" },
    { id: "food-05", category: "comidas", prompt: "Comida que você nunca recusaria", letters: "ABCEFLMPST" },
    { id: "food-06", category: "comidas", prompt: "Melhor acompanhamento", letters: "ABCFMPST" },
    { id: "food-07", category: "comidas", prompt: "Melhor coisa para comer em festa", letters: "ABCFMPST" },
    { id: "food-08", category: "comidas", prompt: "Melhor comida de café da manhã", letters: "ABCFMPST" },

    { id: "game-01", category: "jogos", prompt: "Melhor jogo de todos os tempos", letters: "ABCFGHLMPRSTV" },
    { id: "game-02", category: "jogos", prompt: "Melhor jogo para jogar com amigos", letters: "ABCFGHLMPRSTV" },
    { id: "game-03", category: "jogos", prompt: "Jogo mais viciante", letters: "ABCFGHLMPRSTV" },
    { id: "game-04", category: "jogos", prompt: "Melhor protagonista de videogame", letters: "ACDEGJLMNRST" },
    { id: "game-05", category: "jogos", prompt: "Melhor jogo competitivo", letters: "ABCFGHLMPRSTV" },
    { id: "game-06", category: "jogos", prompt: "Melhor jogo de sobrevivência", letters: "ABCFGHLMPRSTV" },
    { id: "game-07", category: "jogos", prompt: "Melhor franquia de jogos", letters: "ABCFGHLMPRSTV" },
    { id: "game-08", category: "jogos", prompt: "Melhor mapa ou cenário de videogame", letters: "ABCFGHLMPRSTV" },
    { id: "game-09", category: "jogos", prompt: "Melhor vilão de videogame", letters: "ABCDGJMRSW" },
    { id: "game-10", category: "jogos", prompt: "Jogo que merecia uma continuação", letters: "ABCFGHLMPRSTV" },
    { id: "game-11", category: "jogos", prompt: "Melhor jogo de mundo aberto", letters: "ABCFGHLMPRSTV" },
    { id: "game-12", category: "jogos", prompt: "Melhor jogo de corrida", letters: "ABCFGHMNST" },

    { id: "film-01", category: "filmes", prompt: "Melhor filme", letters: "ABCEFGHJMPRSTV" },
    { id: "film-02", category: "filmes", prompt: "Melhor série", letters: "ABCEFGHJMPRSTV" },
    { id: "film-03", category: "filmes", prompt: "Melhor personagem de filme ou série", letters: "ABCDGJLMNRSTV" },
    { id: "film-04", category: "filmes", prompt: "Melhor vilão de filme ou série", letters: "ABCDGJLMNRSTV" },
    { id: "film-05", category: "filmes", prompt: "Filme que você reveria agora", letters: "ABCEFGHJMPRSTV" },
    { id: "film-06", category: "filmes", prompt: "Série mais viciante", letters: "ABCEFGHJMPRSTV" },
    { id: "film-07", category: "filmes", prompt: "Melhor animação", letters: "ABCEFMRT" },
    { id: "film-08", category: "filmes", prompt: "Melhor universo de ficção", letters: "ABCEFGHJMPRSTV" },

    { id: "ani-01", category: "animais", prompt: "Animal mais bonito", letters: "ABCEFGJLMPSTT" },
    { id: "ani-02", category: "animais", prompt: "Animal mais assustador", letters: "ABCEFGJLMPST" },
    { id: "ani-03", category: "animais", prompt: "Melhor animal para representar um time", letters: "ABCEFGJLMPST" },
    { id: "ani-04", category: "animais", prompt: "Animal que você gostaria de ver de perto", letters: "ABCEFGJLMPST" },
    { id: "ani-05", category: "animais", prompt: "Animal mais inteligente", letters: "ABCEFGJLMPST" },
    { id: "ani-06", category: "animais", prompt: "Animal mais forte", letters: "ABCEFGJLMPST" },

    { id: "place-01", category: "lugares", prompt: "Melhor país para viajar", letters: "ABCEFGIJMPST" },
    { id: "place-02", category: "lugares", prompt: "Cidade que você gostaria de conhecer", letters: "ABCFGLMPRSTV" },
    { id: "place-03", category: "lugares", prompt: "Melhor lugar para passar férias", letters: "ABCFGLMPRSTV" },
    { id: "place-04", category: "lugares", prompt: "Lugar mais bonito para visitar", letters: "ABCFGLMPRSTV" },
    { id: "place-05", category: "lugares", prompt: "País mais interessante para morar por um ano", letters: "ABCEFGIJMPST" },
    { id: "place-06", category: "lugares", prompt: "Cidade com mais personalidade", letters: "ABCFGLMPRSTV" },

    { id: "brand-01", category: "marcas", prompt: "Melhor marca de roupa", letters: "ABCFHLMNPRSTV" },
    { id: "brand-02", category: "marcas", prompt: "Marca com os melhores produtos", letters: "ABCFHLMNPRSTV" },
    { id: "brand-03", category: "marcas", prompt: "Marca mais desejada", letters: "ABCFHLMNPRSTV" },
    { id: "brand-04", category: "marcas", prompt: "Marca com melhor identidade", letters: "ABCFHLMNPRSTV" },
    { id: "brand-05", category: "marcas", prompt: "Melhor marca de tênis", letters: "ABCFHLMNPRSTV" },
    { id: "brand-06", category: "marcas", prompt: "Marca que você mais confia", letters: "ABCFHLMNPRSTV" },

    { id: "tech-01", category: "tecnologia", prompt: "Melhor aplicativo", letters: "ACDFGIMNPRSTW" },
    { id: "tech-02", category: "tecnologia", prompt: "Melhor marca de celular", letters: "AGMORSX" },
    { id: "tech-03", category: "tecnologia", prompt: "Tecnologia mais útil no dia a dia", letters: "ABCDFGIMNPRSTW" },
    { id: "tech-04", category: "tecnologia", prompt: "Melhor rede social", letters: "DFILPRSTXY" },
    { id: "tech-05", category: "tecnologia", prompt: "Melhor produto de tecnologia", letters: "ABCDFGIMNPRSTW" },
    { id: "tech-06", category: "tecnologia", prompt: "Empresa de tecnologia mais marcante", letters: "AGIMNSTX" },

    { id: "sport-01", category: "esportes", prompt: "Melhor esporte para assistir", letters: "ABCFHJNSTV" },
    { id: "sport-02", category: "esportes", prompt: "Esporte mais difícil", letters: "ABCFHJNSTV" },
    { id: "sport-03", category: "esportes", prompt: "Melhor atleta", letters: "ACDFGJLMNPRSTV" },
    { id: "sport-04", category: "esportes", prompt: "Esporte mais divertido de praticar", letters: "ABCFHJNSTV" },
    { id: "sport-05", category: "esportes", prompt: "Atleta mais dominante", letters: "ACDFGJLMNPRSTV" },
    { id: "sport-06", category: "esportes", prompt: "Melhor evento esportivo", letters: "CFJOMS" },

    { id: "char-01", category: "personagens", prompt: "Melhor super-herói", letters: "ABCFGHIMSTW" },
    { id: "char-02", category: "personagens", prompt: "Melhor vilão", letters: "ABCDGJLMNRSTV" },
    { id: "char-03", category: "personagens", prompt: "Personagem mais engraçado", letters: "ABCDGJLMNRSTV" },
    { id: "char-04", category: "personagens", prompt: "Personagem que você teria no seu time", letters: "ABCDGJLMNRSTV" },
    { id: "char-05", category: "personagens", prompt: "Personagem mais icônico", letters: "ABCDGJLMNRSTV" },
    { id: "char-06", category: "personagens", prompt: "Personagem mais inteligente", letters: "ABCDGJLMNRSTV" }
  ]
};
